trigger:
  branches:
    include:
      - develop

pool:
  name: NimbusCart-SelfHosted

stages:
  - stage: Build
    displayName: Build and Test

    jobs:
      - job: BuildApplication
        displayName: Build NimbusCart

        steps:
          - checkout: self

          - task: NodeTool@0
            displayName: Install Node.js
            inputs:
              versionSpec: '24.x'

          - script: npm ci
            displayName: Install backend dependencies
            workingDirectory: backend

          - script: npm test
            displayName: Run backend tests
            workingDirectory: backend

          - script: npm ci
            displayName: Install frontend dependencies
            workingDirectory: frontend

          - script: npm run build
            displayName: Build frontend
            workingDirectory: frontend

  - stage: DockerBuild
    displayName: Build Docker Images
    dependsOn: Build
    condition: succeeded()

    jobs:
      - job: BuildDockerImages
        displayName: Build NimbusCart Docker Images

        steps:
          - checkout: self

          - task: Docker@2
            displayName: Build and push backend Docker image
            inputs:
              command: buildAndPush
              containerRegistry: 'sc-nimbuscart-acr'
              repository: 'nimbuscart-backend'
              Dockerfile: 'backend/Dockerfile'
              buildContext: 'backend'
              tags: |
                $(Build.BuildId)

          - task: Docker@2
            displayName: Build and push frontend Docker image
            inputs:
              command: buildAndPush
              containerRegistry: 'sc-nimbuscart-acr'
              repository: 'nimbuscart-frontend'
              Dockerfile: 'frontend/Dockerfile'
              buildContext: 'frontend'
              tags: |
                $(Build.BuildId)